export const Users = [
    {
      id:1,
      profilePicture: "assets/person/11.jpg",
      username: "Sileria Valeria",
    },
    {
      id:2,
      profilePicture: "assets/person/2.jpg",
      username: "Benkey Aren",
    },
    {
      id:3,
      profilePicture: "assets/person/3.jpg",
      username: "Meruru Remini",
    },
    {
      id:4,
      profilePicture: "assets/person/4.jpg",
      username: "Arianne Galifrey",
    },
    {
      id:5,
      profilePicture: "assets/person/5.jpg",
      username: "Yoyo Way",
    },
    {
      id:6,
      profilePicture: "assets/person/6.jpg",
      username: "Oprey Winfrah",
    },
    {
      id:7,
      profilePicture: "assets/person/7.jpg",
      username: "Evy San",
    },
    {
      id:8,
      profilePicture: "assets/person/8.png",
      username: "Volokine Remini",
    },
    {
      id:9,
      profilePicture: "assets/person/9.png",
      username: "Eddea Issaire",
    },
    {
      id:10,
      profilePicture: "assets/person/10.png",
      username: "Esdeath Jager",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Bonjour ! pour l'instant la base de donnée est un fichier .js et il n'y a aucune route de créée :/ Pour naviguer sur ce model changer 'Home' dans App.js par Profile ou Login ou Signup ! Et n'oubliez pas de lire le README ;)",
      photo: "assets/post/100.jpg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      dislike : 0,
      comment: 9,
    },
    {
      id: 2,
      photo: "assets/post/101.jpg",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      dislike : 0,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "assets/post/102.jpg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      dislike : 0,
      comment: 2,
    },
    {
      id: 4,
      photo: "assets/post/103.jpg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      dislike : 0,
      comment: 3,
    },
    {
      id: 5,
      photo: "assets/post/5.jpeg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      dislike : 0,
      comment: 5,
    },
    {
      id: 6,
      photo: "assets/post/6.jpeg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      dislike : 1,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "assets/post/7.jpeg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      dislike : 0,
      comment: 3,
    },
    {
      id: 8,
      photo: "assets/post/8.jpeg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      dislike : 0,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the world by being yourself.",
      photo: "assets/post/9.jpeg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      dislike : 0,
      comment: 2,
    },
    {
      id: 10,
      photo: "assets/post/10.jpeg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      dislike : 1,
      comment: 12,
    },
  ];